apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data-elad-madar-mariadb-0
  namespace: elad-madar
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: elad-madar-storageclass