apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elad-madar-wordpress-ingress
  namespace: elad-madar
spec:
  ingressClassName: elad-madar
  rules:
  - host: aee750e7560244a86894ef72f4630b41-1834286964.us-east-1.elb.amazonaws.com
    http:
      paths:
      - path: /elad
        pathType: Prefix
        backend:
          service:
            name: wordpress-service
            port:
              number: 80