apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: elad-madar-storageclass
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
parameters:
  type: gp3
  encrypted: "true"