{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.nameOverride }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.wordpress.serviceName }}
            port:
              number: {{ .Values.ingress.servicePort }}
{{- end }}