{{- if .Values.ingressClass.enabled }}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.ingressClass.nameOverride }}
spec:
  controller: k8s.io/ingress-nginx
{{- end }}