apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mariadb.serviceName }}
  labels:
    app: mariadb
spec:
  selector:
    app: mariadb
  clusterIP: None
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql