apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.wordpress.serviceName }}
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  type: ClusterIP